# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: eggs 0.0.1 ruby lib

Gem::Specification.new do |s|
  s.name = "eggs"
  s.version = "0.0.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Dave Makena"]
  s.date = "2013-11-05"
  s.description = "Eggs Scrambles and Unscrambles (Encrypts and Decrypts) text and strings, and generates random keys of any length."
  s.email = "davemakena@gmail.com"
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.rdoc"
  ]
  s.files = [
    ".document",
    ".rspec",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "features/eggs.feature",
    "features/step_definitions/eggs_steps.rb",
    "features/support/env.rb",
    "lib/eggs.rb",
    "spec/eggs_spec.rb",
    "spec/spec_helper.rb"
  ]
  s.homepage = "http://github.com/abcbots/eggs"
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = "2.1.10"
  s.summary = "Eggs Scrambles and Unscrambles text and strings"
end

